[package]
name = "strawberry_pattern"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
ndarray = { version = "0.15", features = ["rayon"] }

[dev-dependencies]
approx = "0.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
